### ISSUE TITLE
Verification fails when special characters are received

### ISSUE THREAD

**Issue by velkrissz** [jamius19/paddle-verifier#2] opened 2020-10-06 15:57 UTC
`StringParser.generateInnerValues()` will produce a wrong string length when the string contains a special character. (Eg.: `á`)
You should change `val.length()` to `val.getBytes().length`. (Probably you should use UTF-8 charset.)
Please refer to [this StackOverflow issue](https://stackoverflow.com/questions/2853454/php-unserialize-fails-with-non-encoded-characters)

I implemented the verifier for myself in Kotlin based on this implementation. I found this issue and thought it'll help somebody.
You can receive a special character in the `subscription_payment_succeeded` webhook in the `customer_name` field. (You will receive the cardholder's name.)

**Comment by hpoul** [comment] 2020-10-08 11:41
@velkrissz maybe you could also release/share your kotlin implementation? ;-)

**Comment by jamius19** [comment] 2021-05-11 01:20
Thank you for opening the issue.
I've been having some problems in my personal life hence the (very!) late reply!
My apologies.

I'll look into it.
Have a good day!

**Comment by marcruse** [comment] 2021-10-15 17:32
I also experience the same issue with some special characters in `customer_name` field, hence can not process the webhook.
Have you found any quick workaround while using this library?

**Comment by MarcoSpoerl** [comment] 2022-01-27 20:15
@marcruse My personal quick fix was to copy the three java files to my code base and fix the StringParser locally. And after checking that this fixes my problems, I just opened a pull request to fix the issue.

**Comment by jamius19** [comment] 2022-01-28 15:44
The issue is fixed thanks to the contributions from @MarcoSpoerl 
Please see pull req #4

**Comment by jamius19** [comment] 2022-01-28 15:44
Closing this issue.

**Closed as completed by jamius19** 2022-01-28 15:44 UTC
Labels: bug
